# Generated by Django 4.2.6 on 2023-10-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='año',
            new_name='anio',
        ),
    ]
