# Generated by Django 4.2.6 on 2023-10-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_año_paleta_anio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paleta',
            new_name='Llavero',
        ),
        migrations.RenameField(
            model_name='llavero',
            old_name='anio',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='llavero',
            old_name='marca',
            new_name='modelo',
        ),
    ]
