# Generated by Django 4.2.6 on 2023-10-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_llavero_cantidad_alter_llavero_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Llavero',
            new_name='Pedido',
        ),
    ]
