# Generated by Django 4.2.6 on 2023-11-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_soportecelulares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
