# Generated by Django 4.2.6 on 2023-11-12 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0010_llaveros_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llaveros', models.ManyToManyField(blank=True, related_name='carritos', to='inicio.llaveros')),
                ('portamemorias', models.ManyToManyField(blank=True, related_name='carritos', to='inicio.portamemorias')),
                ('soportecelulares', models.ManyToManyField(blank=True, related_name='carritos', to='inicio.soportecelulares')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
