# Generated by Django 4.2.6 on 2023-11-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llaveros',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='llaveros',
            field=models.ManyToManyField(blank=True, related_name='carrito', to='inicio.llaveros'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='portamemorias',
            field=models.ManyToManyField(blank=True, related_name='carrito', to='inicio.portamemorias'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='soportecelulares',
            field=models.ManyToManyField(blank=True, related_name='carrito', to='inicio.soportecelulares'),
        ),
    ]
