# Generated by Django 4.2.6 on 2023-11-12 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0015_remove_carrito_llaveros_remove_carrito_portamemorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveros',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
