# Generated by Django 4.2.6 on 2023-11-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_rename_usuario_llaveros_sorete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llaveros',
            old_name='sorete',
            new_name='usuario',
        ),
    ]
