# Generated by Django 4.2.6 on 2023-11-17 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0019_portamemorias_usuario_soportecelulares_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveros',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portamemorias',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='soportecelulares',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
