# Generated by Django 4.2.6 on 2023-11-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0020_llaveros_fecha_pedido_portamemorias_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llaveros',
            old_name='fecha_pedido',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='portamemorias',
            name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='soportecelulares',
            name='fecha_pedido',
        ),
    ]
