# Generated by Django 4.2.6 on 2023-11-17 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0021_rename_fecha_pedido_llaveros_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portamemorias',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='soportecelulares',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
