# Generated by Django 4.2.6 on 2023-11-18 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0023_remove_llaveros_descripción_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llaveros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Descripción por defecto'),
        ),
        migrations.AlterField(
            model_name='portamemorias',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Descripción por defecto'),
        ),
        migrations.AlterField(
            model_name='soportecelulares',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Descripción por defecto'),
        ),
    ]
