# Generated by Django 4.2.6 on 2023-11-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0024_alter_llaveros_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llaveros',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portamemorias',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soportecelulares',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
