# Generated by Django 4.2.6 on 2023-11-18 17:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0025_alter_llaveros_id_alter_portamemorias_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llaveros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='llaveros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portamemorias',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='portamemorias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soportecelulares',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='soportecelulares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
