# Generated by Django 4.2.6 on 2023-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0026_alter_llaveros_descripcion_alter_llaveros_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='llaveros',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portamemorias',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soportecelulares',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
