# Generated by Django 4.2.6 on 2023-11-18 17:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0028_alter_llaveros_id_alter_portamemorias_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llaveros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='no hay descripción'),
        ),
        migrations.AlterField(
            model_name='portamemorias',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='no hay descripción'),
        ),
        migrations.AlterField(
            model_name='soportecelulares',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='no hay descripción'),
        ),
    ]
