# Generated by Django 4.2.6 on 2023-11-13 23:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosExtraDeUsuasio',
            new_name='DatosExtra',
        ),
    ]
