# Generated by Django 4.2.6 on 2023-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
