# Generated by Django 4.2.6 on 2023-11-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_datosextra_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
